spring.application.name=panelpraktyk
spring.h2.console.enabled=true
spring.jackson.deserialization.accept-single-value-as-array=true
spring.datasource.username=user
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update